volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql